language: objective-c
osx_image: xcode10.1
cache:
  - bundler
  - cocoapods
before_install:
  - gem update --system
  - gem install bundler
install:
  - bundle install
script:
  - fastlane beta

# Image defaults:
#
# macOS   10.13.6
# git     2.19.1
# bash    3.2.57
# ruby    2.3.5, 2.4.5
# nodejs  v10.13.0, v4.9.1, v5.12.0, v6.14.4, v8.12.0
# Maven   3.5.4  (mvn)
# Java    11.0.1
# rvm     1.29.4 