opt_out_usage

setup_travis if is_ci?

default_platform(:ios)

platform :ios do
  desc "Building iOS App"
  lane :beta do
    get_certificates
    get_provisioning_profile
    build_app(
      scheme: "AwesomeApp",
      project: "ios/AwesomeApp.xcodeproj",
      include_bitcode: false,
    )
  end
end
