opt_out_usage

setup_travis if is_ci?

default_platform(:ios)

platform :ios do
  desc "Building iOS App"
  lane :beta do
    build_app(
      scheme: "AwesomeApp", 
      workspace: "ios/AwesomeApp.xcworkspace", 
      include_bitcode: false)
  end
end
